/**
 * @author Maria Fernanda Serna
 */

export const GET_LIST_REPOS_USER_REQUEST = 'GET_LIST_REPOS_USER_REQUEST';
export const GET_LIST_REPOS_USER_REQUEST_FAIL =
  'GET_LIST_REPOS_USER_REQUEST_FAIL';
export const GET_LIST_REPOS_USER_REQUEST_SUCCESS =
  'GET_LIST_REPOS_USER_REQUEST_SUCCESS';
